training:
  optimizer:
    name: 'SGD'
    params:
      lr: 0.0001
      momentum: 0.9
      weight_decay: 0.0001
  criterion:
    name: "DiceLoss"
    params: {}
  scheduler:
    factor: 0.5
    patience: 10
  epochs: 100  
  # epochs: 300
model:
  load_weights: false
  name: 'MISSFormer'
  params:
    in_ch: 3
    num_classes: 2
  class: 'models._missformer.MISSFormer.MISSFormer'  
# preprocess: