training:
  optimizer:
#     name: 'Adam'
#     params:
#       lr: 0.0001
    name: "SGD"
    params:
      lr: 0.0001
      momentum: 0.9
      weight_decay: 0.0001
  criterion:
    name: "DiceLoss"
    params: {}
  scheduler:
    factor: 0.5
    patience: 10
  epochs: 100   
model:
  load_weights: false
  name: 'VisionTransformer'
  params:
    img_size: 224
    num_classes: 2
    # preprocess:
  # class: 'models._transunet.vit_seg_modeling_c4.VisionTransformer'  
  class: 'models._transunet.vit_seg_modeling.VisionTransformer'
  